# Generated by Django 4.0.5 on 2022-07-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='observations',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
